### PR TITLE
refactor: remove unnecessary `useFetchWithCache` hook

### PR DESCRIPTION
**Pull request by trankhacvy**
#### What's this PR do?

- [x] Remove `useFetchWithCache` hook
- [x] Rename some variables for better meaning.

#### Any background context you want to provide? (if appropriate)

- [`swr 2.0`](https://swr.vercel.app/blog/swr-v2#isloading) introduced a new state variable `isLoading` which indicates **if the request is still ongoing, and there is no data loaded yet**. The result is we don't need to check if both `data` and `error` are `undefined` to determine if it was the initial loading state. So the `useFetchWithCache` hook is unnecessary and can be removed.
- We use `useXXX` hook pattern to fetch data so I think the exported data should be have a meaningful name which relate to `useXXX` hook
 
```
export function useFetchUsers() {
  const { data, ...rest } = useSWR(SWR_KEY, () => client.getUsers())

  return {
    users: data, // rename `data` variable to what we intend to export
    ...rest,
  }
}
```

### CODE REVIEW

**Comment by trankhacvy** [comment]
@zlatanpham [swr 2.0](https://swr.vercel.app/blog/swr-v2#useswrmutation) also introduced a new `useSWRMutation` hook. I think we can add create or edit feature to demonstrate how this hook works (the `mutate` -> `revalidate` pattern)

**Comment by zlatanpham** [comment]
> * [`swr 2.0`](https://swr.vercel.app/blog/swr-v2#isloading) introduced a new state variable `isLoading` which indicates **if the request is still ongoing, and there is no data loaded yet**. The result is we don't need to check if both `data` and `error` are `undefined` to determine if it was the initial loading state. So the `useFetchWithCache` hook is unnecessary and can be removed.

Is this still correct for the meaning of FIRST loading? The `isFirstLoading` is different from `isLoading`. There is a few UI cases we need the distinguished between whether it's the first load. For example, in the case of rendering a table
1. Display skeleton for the first loading
2. If a new API call, instead, fade out the table 

This specific use case reveals the reason we need the FIRST loading state and I don't think the `isLoading` can cover the case.

**Comment by trankhacvy** [comment]
> 1. Display skeleton for the first loading
> 2. If a new API call, instead, fade out the table

1/ This is the case we use `isLoading`. 
2/ In this case, we use `isValidating` 

The code will look like
```
if(isLoading) return <Skeleton />

return <Table  className={isValidating ? 'fade-out' : ''}  />

```
Please refer to this [state machine](https://swr.vercel.app/docs/advanced/understanding) for better understanding.

**Comment by zlatanpham** [comment]
> 2/ In this case, we use `isValidating`

The API call can happen due to `mutate` call but it can also happen when keys change, which will trigger `isLoading` state change and render the `skeleton`. - https://swr.vercel.app/docs/advanced/understanding#key-change

**Comment by zlatanpham** [comment]
But I think the example of `keepPreviousData` looks promising - https://swr.vercel.app/docs/advanced/understanding#return-previous-data-for-better-ux

**Comment by trankhacvy** [comment]
Yep, we can apply this pattern to solve the case when the key is changed. The intent of this PR is to remove unnecessary hook which cost us one more re-render. I think swr gives us enough options to handle our cases.

**Review by zlatanpham — APPROVED** [review]

**Pull request merged**
